spring:
  h2.console.enabled: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: create

institute:
  nameAndCodes:
    - name: 주택도시기금
      code: jutek
    - name: 국민은행
      code: kookmin
    - name: 우리은행
      code: woori
    - name: 신한은행
      code: shinhan
    - name: 한국시티은행
      code: hankookcity
    - name: 하나은행
      code: hana
    - name: 농협은행/수협은행
      code: nhsh
    - name: 외환은행
      code: exchange
    - name: 기타은행
      code: etc
#  nameToCode:
#    주택도시기금: jutek
#    국민은행: kookmin
#    우리은행: woori
#    신한은행: shinhan
#    한국시티은행: hankookcity
#    하나은행: hana
#    농협은행/수협은행: nhsh
#    외환은행: exchange
#    기타은행: etc
